version: 2
updates:
  - package-ecosystem: "npm"
    cooldown:
      default-days: 10
    directory: "/"
    schedule:
      interval: "daily"
      timezone: Australia/Sydney
    open-pull-requests-limit: 10
    reviewers:
      - "r-k-b"
  - package-ecosystem: "elm"
    cooldown:
      default-days: 10
    directory: "/"
    schedule:
      interval: "daily"
      timezone: Australia/Sydney
    open-pull-requests-limit: 10
    reviewers:
      - "r-k-b"
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 10
    directory: "/"
    schedule:
      interval: "daily"
      timezone: Australia/Sydney
    open-pull-requests-limit: 10
    reviewers:
      - r-k-b
